export interface DialCodeWithLength {
  country?: string | number | null | undefined;
  phLengthMax?: number | null;
  phLengthMin?: number | null;
  phLength?: string | number | null | undefined;
  CountryCode?: string | number | null | undefined;
  phLength_InternationalPrefix?: string | number | null | undefined;
  phLength_NationalPrefix?: string | number | null | undefined;
  Notes?: string | number | null | undefined;
}

/**
 * A dial-code row adapted for a select/autocomplete control.
 * Lived in `auth.model.ts` until the auth layer was removed; it is really a
 * property of this table, so it lives with it now.
 */
export type CountryCodeOption = DialCodeWithLength & { value: string; label: string };

export const dialCodeWithLength = [
  {
    country: 'India',
    phLengthMax: 10,
    phLengthMin: 7,
    phLength: '7 to 10',
    CountryCode: '+91',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'China',
    phLengthMax: 12,
    phLengthMin: 5,
    phLength: '5 to 12',
    CountryCode: '+86',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'United States',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: 10,
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes:
      'Eastern Time UTC-5/DST-4; Central Time UTC-6/DST-5; Mountain Time UTC-7; Pacific Time UTC-8/DST-7; Alaska UTC-9/DST-8; Hawaiian UTC-10.',
  },
  {
    country: 'Indonesia',
    phLengthMax: 10,
    phLengthMin: 5,
    phLength: '5 to 10',
    CountryCode: '+62',
    phLength_InternationalPrefix: 1.008,
    phLength_NationalPrefix: null,
    Notes:
      'Western Indonesia including Sumatra, Java, Madura and Bali UTC+7; Central Indonesia including Kalimantan (Borneo), Sulawesi (Celebes) and Nusatengarra (Lesser Sunda) UTC+8; Eastern Indonesia including Maluku (Moluccas) and Irianjaya (Irian) UTC+9.',
  },
  {
    country: 'Pakistan',
    phLengthMax: 11,
    phLengthMin: 8,
    phLength: '8 to 11',
    CountryCode: '+92',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Nigeria',
    phLengthMax: 10,
    phLengthMin: 7,
    phLength: '7 to 10',
    CountryCode: '+234',
    phLength_InternationalPrefix: 9,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Brazil',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: 10,
    CountryCode: '+55',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: 'Other states UTC-3 (no change).',
  },
  {
    country: 'Bangladesh',
    phLengthMax: 10,
    phLengthMin: 6,
    phLength: '6 to 10',
    CountryCode: '+880',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Russia',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: 10,
    CountryCode: '+7',
    phLength_InternationalPrefix: 810,
    phLength_NationalPrefix: 8,
    Notes:
      'Kaliningrad UTC +2/DST+3; Moscow, St. Petersburg, Astrakhan, Izhevsk, Samara UTC+3/DST+4; Perm, Nizhnevartovsk UTC+5/DST+6; Novosibirsk, Omsk UTC+6/DST+7; Norilsk, Kyzyl UTC+7/DST+8; Bratsk, Ulan-Ude UTC+8/DST+9; Chita, Yakutsk UTC+9/DST+10; Khabarovsk, Vladivostok, Yuzhno-Sakhalinsk UTC+10/DST+11; Magadan, Kamchatka UTC+11/DST+12.',
  },
  {
    country: 'Ethiopia',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+251',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Mexico',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: 10,
    CountryCode: '+52',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: 1,
    Notes:
      'Baja California Norte UTC-8/DST-7; Baja California Sur, Chihuahua, Nayarit UTC-7/DST-6.',
  },
  {
    country: 'Japan',
    phLengthMax: 13,
    phLengthMin: 5,
    phLength: '5 to 13',
    CountryCode: '+81',
    phLength_InternationalPrefix: 10,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Egypt',
    phLengthMax: 9,
    phLengthMin: 7,
    phLength: '7 to 9',
    CountryCode: '+20',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Philippines',
    phLengthMax: 10,
    phLengthMin: 8,
    phLength: '8 to 10',
    CountryCode: '+63',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'DR Congo',
    phLengthMax: 9,
    phLengthMin: 5,
    phLength: '5 to 9',
    CountryCode: '+243',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Vietnam',
    phLengthMax: 10,
    phLengthMin: 7,
    phLength: '7 to 10',
    CountryCode: '+84',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Iran',
    phLengthMax: 10,
    phLengthMin: 6,
    phLength: '6 to 10',
    CountryCode: '+98',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Turkey',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: 10,
    CountryCode: '+90',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Germany',
    phLengthMax: 13,
    phLengthMin: 6,
    phLength: '6 to 13',
    CountryCode: '+49',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Thailand',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 or 9',
    CountryCode: '+66',
    phLength_InternationalPrefix: 1,
    phLength_NationalPrefix: null,
    Notes:
      "The '0' is used on all domestic calls, including in the same city, but is omitted when dialling from other countries.",
  },
  {
    country: 'United Kingdom',
    phLengthMax: 10,
    phLengthMin: 7,
    phLength: '7 to 10',
    CountryCode: '+44',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Tanzania',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+255',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'France',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+33',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      "The '0' is used on all domestic calls, including in the same city, but is omitted when dialling from other countries.",
  },
  {
    country: 'South Africa',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+27',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      "The '0' is used on all domestic calls, including in the same city, but is omitted when dialling from other countries.",
  },
  {
    country: 'Italy',
    phLengthMax: 11,
    phLengthMin: null,
    phLength: 'up to 11',
    CountryCode: '+39',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      "When dialling from Italy to San Marino, the subscriber number must be prefixed by '0549' instead of '00378'. When dialling from San Marino to Italy, the complete national subscriber number must be used, without prefixing the number by '0039'.",
  },
  {
    country: 'Kenya',
    phLengthMax: 10,
    phLengthMin: 6,
    phLength: '6 to 10',
    CountryCode: '+254',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      'When dialling between Kenya, Tanzania and Uganda the national (significant) number must be prefixed by 005 for Kenya, by 006 for Uganda and by 007 for Tanzania',
  },
  {
    country: 'Myanmar',
    phLengthMax: 9,
    phLengthMin: 7,
    phLength: '7 to 9',
    CountryCode: '+95',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Colombia',
    phLengthMax: 10,
    phLengthMin: 8,
    phLength: '8 or 10',
    CountryCode: '+57',
    phLength_InternationalPrefix: '009/007/005',
    phLength_NationalPrefix: '09/07/05',
    Notes: null,
  },
  {
    country: 'South Korea',
    phLengthMax: 11,
    phLengthMin: 8,
    phLength: '8 to 11',
    CountryCode: '+82',
    phLength_InternationalPrefix: 1.002,
    phLength_NationalPrefix: 0.082,
    Notes: null,
  },
  {
    country: 'Sudan',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+249',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Uganda',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+256',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      'When dialling between Kenya, Tanzania and Uganda the national (significant) number must be prefixed by 005 for Kenya, by 006 for Uganda and by 007 for Tanzania',
  },
  {
    country: 'Spain',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+34',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Algeria',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 or 9',
    CountryCode: '+213',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Iraq',
    phLengthMax: 10,
    phLengthMin: 8,
    phLength: '8 to 10',
    CountryCode: '+964',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Argentina',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: 10,
    CountryCode: '+54',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Afghanistan',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+93',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Yemen',
    phLengthMax: 9,
    phLengthMin: 6,
    phLength: '6 to 9',
    CountryCode: '+967',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Canada',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: 10,
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes:
      'Alberta UTC-7/DST-6; British Columbia UTC-8/DST-7; Manitoba UTC-6/DST-5; New Brunswick, Nova Scotia UTC-4/DST-3;Newfoundland UTC-3.30/DST-2.30; Ontario, Quebec UTC-5/DST-4.',
  },
  {
    country: 'Poland',
    phLengthMax: 9,
    phLengthMin: 6,
    phLength: '6 to 9',
    CountryCode: '+48',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Morocco',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+212',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      "The '0' is used on all domestic calls, including in the same city, but is omitted when dialling from other countries.",
  },
  {
    country: 'Angola',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+244',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Ukraine',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+380',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Uzbekistan',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+998',
    phLength_InternationalPrefix: 810,
    phLength_NationalPrefix: 8,
    Notes: null,
  },
  {
    country: 'Malaysia',
    phLengthMax: 9,
    phLengthMin: 7,
    phLength: '7 to 9',
    CountryCode: '+60',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      "When dialling from Singapore to Malaysia, the area code and subscriber number must be prefixed by '020' instead of '00160'. When dialling from Malaysia to Singapore, the subscriber number must be prefixed by '02' instead of '0065'.",
  },
  {
    country: 'Mozambique',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 to 9',
    CountryCode: '+258',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Ghana',
    phLengthMax: 9,
    phLengthMin: 5,
    phLength: '5 to 9',
    CountryCode: '+233',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Peru',
    phLengthMax: 11,
    phLengthMin: 8,
    phLength: '8 to 11',
    CountryCode: '+51',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Saudi Arabia',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 to 9',
    CountryCode: '+966',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Madagascar',
    phLengthMax: 10,
    phLengthMin: 9,
    phLength: '9 to 10',
    CountryCode: '+261',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Ivory Coast',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+225',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Nepal',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 to 9',
    CountryCode: '+977',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Cameroon',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+237',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Venezuela',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: 10,
    CountryCode: '+58',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Niger',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+227',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Australia',
    phLengthMax: 15,
    phLengthMin: 5,
    phLength: '5 to 15',
    CountryCode: '+61',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: null,
    Notes:
      'Includes Cocos-Keeling Islands(UTC+6.30) and Christmas Island (UTC+7). Western Australia (UTC+8).',
  },
  {
    country: 'North Korea',
    phLengthMax: 17,
    phLengthMin: 6,
    phLength: '6 to 17',
    CountryCode: '+850',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Syria',
    phLengthMax: 10,
    phLengthMin: 8,
    phLength: '8 to 10',
    CountryCode: '+963',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Mali',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+223',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Burkina Faso',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+226',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Taiwan',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 to 9',
    CountryCode: '+886',
    phLength_InternationalPrefix: 2,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Sri Lanka',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+94',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Malawi',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 or 8',
    CountryCode: '+265',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Zambia',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+260',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Kazakhstan',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: 10,
    CountryCode: '+7',
    phLength_InternationalPrefix: 810,
    phLength_NationalPrefix: 8,
    Notes: null,
  },
  {
    country: 'Chad',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+235',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Chile',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 to 9',
    CountryCode: '+56',
    phLength_InternationalPrefix: '1YZ0',
    phLength_NationalPrefix: '1YZ',
    Notes: 'YZ : long-distance operator code.',
  },
  {
    country: 'Romania',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+40',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Somalia',
    phLengthMax: 8,
    phLengthMin: 5,
    phLength: '5 to 8',
    CountryCode: '+252',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Senegal',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+221',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Guatemala',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+502',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Netherlands',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+31',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Ecuador',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+593',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Cambodia',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+855',
    phLength_InternationalPrefix: '001, 007',
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Zimbabwe',
    phLengthMax: 10,
    phLengthMin: 5,
    phLength: '5 to 10',
    CountryCode: '+263',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Guinea',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+224',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Benin',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+229',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Rwanda',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+250',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Burundi',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+257',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Bolivia',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+591',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Tunisia',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+216',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Haiti',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+509',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Belgium',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 to 9',
    CountryCode: '+32',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      "The '0' is used on all domestic calls, including in the same city, but is omitted when dialling from other countries.",
  },
  {
    country: 'Jordan',
    phLengthMax: 9,
    phLengthMin: 5,
    phLength: '5 to 9',
    CountryCode: '+962',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Dominican Republic',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(809/829) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'United Arab Emirates',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 to 9',
    CountryCode: '+971',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Cuba',
    phLengthMax: 8,
    phLengthMin: 6,
    phLength: '6 to 8',
    CountryCode: '+53',
    phLength_InternationalPrefix: 119,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Honduras',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+504',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Czech Republic',
    phLengthMax: 12,
    phLengthMin: 4,
    phLength: '4 to 12',
    CountryCode: '+420',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Sweden',
    phLengthMax: 13,
    phLengthMin: 7,
    phLength: '7 to 13',
    CountryCode: '+46',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Tajikistan',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+992',
    phLength_InternationalPrefix: 810,
    phLength_NationalPrefix: 8,
    Notes:
      'When dialling between Kenya, Tanzania and Uganda the national (significant) number must be prefixed by 005 for Kenya, by 006 for Uganda and by 007 for Tanzania',
  },
  {
    country: 'Papua New Guinea',
    phLengthMax: 11,
    phLengthMin: 4,
    phLength: '4 to 11',
    CountryCode: '+675',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Portugal',
    phLengthMax: 11,
    phLengthMin: 9,
    phLength: '9 or 11',
    CountryCode: '+351',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Azerbaijan',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 to 9',
    CountryCode: '+994',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Greece',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: 10,
    CountryCode: '+30',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      "The '0' is used on all domestic calls, including in the same city, but is omitted when dialling from other countries.",
  },
  {
    country: 'Hungary',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 to 9',
    CountryCode: '+36',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: 6,
    Notes:
      'Subscriber numbers on PSTN and analogue mobile network consist of 8 digits and those on the mobile network consist of 9 digits.',
  },
  {
    country: 'Togo',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+228',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Israel',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 to 9',
    CountryCode: '+972',
    phLength_InternationalPrefix: '12,013,014',
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Austria',
    phLengthMax: 13,
    phLengthMin: 4,
    phLength: '4 to 13',
    CountryCode: '+43',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Belarus',
    phLengthMax: 10,
    phLengthMin: 9,
    phLength: '9 to 10',
    CountryCode: '+375',
    phLength_InternationalPrefix: 810,
    phLength_NationalPrefix: 8,
    Notes: null,
  },
  {
    country: 'Switzerland',
    phLengthMax: 12,
    phLengthMin: 4,
    phLength: '4 to 12',
    CountryCode: '+41',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      "The '0' is used on all domestic calls, including in the same city, but is omitted when dialling from other countries.",
  },
  {
    country: 'Sierra Leone',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+232',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Laos',
    phLengthMax: 10,
    phLengthMin: 8,
    phLength: '8 to 10',
    CountryCode: '+856',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Turkmenistan',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+993',
    phLength_InternationalPrefix: 810,
    phLength_NationalPrefix: 8,
    Notes: null,
  },
  {
    country: 'Hong Kong',
    phLengthMax: 9,
    phLengthMin: 4,
    phLength: '4, 8 to 9',
    CountryCode: '+852',
    phLength_InternationalPrefix: 1,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Libya',
    phLengthMax: 9,
    phLengthMin: 8,
    phLength: '8 to 9',
    CountryCode: '+218',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Kyrgyzstan',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+996',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Paraguay',
    phLengthMax: 9,
    phLengthMin: 5,
    phLength: '5 to 9',
    CountryCode: '+595',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Nicaragua',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+505',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Bulgaria',
    phLengthMax: 9,
    phLengthMin: 7,
    phLength: '7 to 9',
    CountryCode: '+359',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      "The '0' is used on all domestic calls, including in the same city, but is omitted when dialling from other countries.",
  },
  {
    country: 'Serbia',
    phLengthMax: 12,
    phLengthMin: 4,
    phLength: '4 to 12',
    CountryCode: '+381',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'El Salvador',
    phLengthMax: 11,
    phLengthMin: 7,
    phLength: '7, 8 or 11',
    CountryCode: '+503',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      'The seven and eleven digit schemes are solely for numbers that do not entail any charge for the subscriber making the call (800) or for numbers that involve a surcharge for subscriber A (900). All other numbers have a fixed eight digit scheme.',
  },
  {
    country: 'Denmark',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+45',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Singapore',
    phLengthMax: 12,
    phLengthMin: 8,
    phLength: '8 to 12',
    CountryCode: '+65',
    phLength_InternationalPrefix: 1.008,
    phLength_NationalPrefix: null,
    Notes:
      "When dialling from Singapore to Malaysia, the area code and subscriber number must be prefixed by '020' instead of '00160'. When dialling from Malaysia to Singapore, the subscriber number must be prefixed by '02' instead of '0065'.",
  },
  {
    country: 'Lebanon',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 to 8',
    CountryCode: '+961',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Finland',
    phLengthMax: 12,
    phLengthMin: 5,
    phLength: '5 to 12',
    CountryCode: '+358',
    phLength_InternationalPrefix: '00,99X',
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Liberia',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 to 8',
    CountryCode: '+231',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Norway',
    phLengthMax: 8,
    phLengthMin: 5,
    phLength: '5 or 8',
    CountryCode: '+47',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Slovakia',
    phLengthMax: 9,
    phLengthMin: 4,
    phLength: '4 to 9',
    CountryCode: '+421',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Central African Republic',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+236',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Oman',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 to 8',
    CountryCode: '+968',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Ireland',
    phLengthMax: 11,
    phLengthMin: 7,
    phLength: '7 to 11',
    CountryCode: '+353',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      "When dialling from Ireland to Northern Ireland, the area code used should be '048' instead of '0044 28'.",
  },
  {
    country: 'New Zealand',
    phLengthMax: 10,
    phLengthMin: 3,
    phLength: '3 to 10',
    CountryCode: '+64',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Mauritania',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+222',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Costa Rica',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+506',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Kuwait',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 or 8',
    CountryCode: '+965',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Panama',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 or 8',
    CountryCode: '+507',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: 'Seven digits for the fixed network and eight digits for the mobile network.',
  },
  {
    country: 'Croatia',
    phLengthMax: 12,
    phLengthMin: 8,
    phLength: '8 to 12',
    CountryCode: '+385',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Georgia',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+995',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Eritrea',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+291',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Mongolia',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 to 8',
    CountryCode: '+976',
    phLength_InternationalPrefix: 1,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Uruguay',
    phLengthMax: 11,
    phLengthMin: 4,
    phLength: '4 to 11',
    CountryCode: '+598',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Puerto Rico',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(787/939) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Bosnia and Herzegovina',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+387',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Qatar',
    phLengthMax: 8,
    phLengthMin: 3,
    phLength: '3 to 8',
    CountryCode: '+974',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Moldova',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+373',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Namibia',
    phLengthMax: 10,
    phLengthMin: 6,
    phLength: '6 to 10',
    CountryCode: '+264',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Armenia',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+374',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Lithuania',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+370',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Jamaica',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(876) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Albania',
    phLengthMax: 9,
    phLengthMin: 3,
    phLength: '3 to 9',
    CountryCode: '+355',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Gambia',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+220',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Gabon',
    phLengthMax: 7,
    phLengthMin: 6,
    phLength: '6 or 7',
    CountryCode: '+241',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Botswana',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 to 8',
    CountryCode: '+267',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Lesotho',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+266',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Slovenia',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+386',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Equatorial Guinea',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+240',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Latvia',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 or 8',
    CountryCode: '+371',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Bahrain',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+973',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Trinidad and Tobago',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(868) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Estonia',
    phLengthMax: 10,
    phLengthMin: 7,
    phLength: '7 to 10',
    CountryCode: '+372',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Cyprus',
    phLengthMax: 11,
    phLengthMin: 8,
    phLength: '8 or 11',
    CountryCode: '+357',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: '11 digits for voice-mail services only.',
  },
  {
    country: 'Mauritius',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+230',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      'Carrier pre-selection has been introduced in Mauritius since 1 January 2005. The international prefix “00” may be used only by those subscribers who have pre-selected an International Long Distance (ILD) carrier. For subscribers who have not pre-selected any carrier, their international calls made using the prefix “00” are not allowed through.All subscribers may however select the ILD carrier of their choice on a Call-by-Call basis by using the carrier prefix assigned to the selected carrier, by the ICTA (ILD Carrier Prefix: 020, 022, 030, 033, 040, 050, 060, 070).',
  },
  {
    country: 'Eswatini',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 to 8',
    CountryCode: '+268',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Djibouti',
    phLengthMax: 6,
    phLengthMin: 6,
    phLength: 6,
    CountryCode: '+253',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Fiji',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+679',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Comoros',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+269',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Guyana',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+592',
    phLength_InternationalPrefix: 1,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Solomon Islands',
    phLengthMax: 5,
    phLengthMin: 5,
    phLength: 5,
    CountryCode: '+677',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Bhutan',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 to 8',
    CountryCode: '+975',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Macau',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 to 8',
    CountryCode: '+853',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Luxembourg',
    phLengthMax: 11,
    phLengthMin: 4,
    phLength: '4 to 11',
    CountryCode: '+352',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Montenegro',
    phLengthMax: 12,
    phLengthMin: 4,
    phLength: '4 to 12',
    CountryCode: '+382',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Suriname',
    phLengthMax: 7,
    phLengthMin: 6,
    phLength: '6 to 7',
    CountryCode: '+597',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Malta',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+356',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Maldives',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+960',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Cape Verde',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+238',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Brunei',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+673',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Belize',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+501',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Bahamas',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(242) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Iceland',
    phLengthMax: 9,
    phLengthMin: 7,
    phLength: '7 or 9',
    CountryCode: '+354',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Guadeloupe',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+590',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Martinique',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+596',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Vanuatu',
    phLengthMax: 7,
    phLengthMin: 5,
    phLength: '5 or 7',
    CountryCode: '+678',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'French Guiana',
    phLengthMax: 9,
    phLengthMin: 9,
    phLength: 9,
    CountryCode: '+594',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'New Caledonia',
    phLengthMax: 6,
    phLengthMin: 6,
    phLength: 6,
    CountryCode: '+687',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Barbados',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(246) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'French Polynesia',
    phLengthMax: 6,
    phLengthMin: 6,
    phLength: 6,
    CountryCode: '+689',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Sao Tome and Principe',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+239',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Samoa',
    phLengthMax: 7,
    phLengthMin: 3,
    phLength: '3 to 7',
    CountryCode: '+685',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Curacao',
    phLengthMax: 8,
    phLengthMin: 7,
    phLength: '7 to 8',
    CountryCode: '+599',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Saint Lucia',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(758) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Guam',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(671) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Kiribati',
    phLengthMax: 5,
    phLengthMin: 5,
    phLength: 5,
    CountryCode: '+686',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Seychelles',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+248',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Grenada',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(473) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Micronesia',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+691',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Aruba',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+297',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Tonga',
    phLengthMax: 7,
    phLengthMin: 5,
    phLength: '5 or 7',
    CountryCode: '+676',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Saint Vincent and the Grenadines',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(784) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Antigua and Barbuda',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(268) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'United States Virgin Islands',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(340) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Andorra',
    phLengthMax: 9,
    phLengthMin: 6,
    phLength: '6, 8 or 9',
    CountryCode: '+376',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Cayman Islands',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(345) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Dominica',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(767) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Bermuda',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(441) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Greenland',
    phLengthMax: 6,
    phLengthMin: 6,
    phLength: 6,
    CountryCode: '+299',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Faroe Islands',
    phLengthMax: 6,
    phLengthMin: 6,
    phLength: 6,
    CountryCode: '+298',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Saint Kitts and Nevis',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(869) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'American Samoa',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(684) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Turks and Caicos Islands',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(649) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Sint Maarten',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(721) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Liechtenstein',
    phLengthMax: 9,
    phLengthMin: 7,
    phLength: '7 to 9',
    CountryCode: '+423',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'British Virgin Islands',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(284) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Gibraltar',
    phLengthMax: 8,
    phLengthMin: 8,
    phLength: 8,
    CountryCode: '+350',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Monaco',
    phLengthMax: 9,
    phLengthMin: 5,
    phLength: '5 to 9',
    CountryCode: '+377',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Marshall Islands',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+692',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'San Marino',
    phLengthMax: 10,
    phLengthMin: 6,
    phLength: '6 to 10',
    CountryCode: '+378',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      "When dialling from Italy to San Marino, the subscriber number must be prefixed by '0549' instead of '00378'. When dialling from San Marino to Italy, the complete national subscriber number must be used, without prefixing the number by '0039'.",
  },
  {
    country: 'Palau',
    phLengthMax: 7,
    phLengthMin: 7,
    phLength: 7,
    CountryCode: '+680',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Anguilla',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(264) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Cook Islands',
    phLengthMax: 5,
    phLengthMin: 5,
    phLength: 5,
    CountryCode: '+682',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Nauru',
    phLengthMax: 7,
    phLengthMin: 4,
    phLength: '4 or 7',
    CountryCode: '+674',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Wallis and Futuna',
    phLengthMax: 6,
    phLengthMin: 6,
    phLength: 6,
    CountryCode: '+681',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Tuvalu',
    phLengthMax: 6,
    phLengthMin: 5,
    phLength: '5 or 6',
    CountryCode: '+688',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Saint Pierre and Miquelon',
    phLengthMax: 6,
    phLengthMin: 6,
    phLength: 6,
    CountryCode: '+508',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Montserrat',
    phLengthMax: 10,
    phLengthMin: 10,
    phLength: '(664) + 7',
    CountryCode: '+1',
    phLength_InternationalPrefix: 11,
    phLength_NationalPrefix: 1,
    Notes: null,
  },
  {
    country: 'Falkland Islands',
    phLengthMax: 5,
    phLengthMin: 5,
    phLength: 5,
    CountryCode: '+500',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Tokelau',
    phLengthMax: 4,
    phLengthMin: 4,
    phLength: 4,
    CountryCode: '+690',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Niue',
    phLengthMax: 4,
    phLengthMin: 4,
    phLength: 4,
    CountryCode: '+683',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes: null,
  },
  {
    country: 'Vatican City',
    phLengthMax: 11,
    phLengthMin: null,
    phLength: 'up to 11',
    CountryCode: '+39',
    phLength_InternationalPrefix: null,
    phLength_NationalPrefix: null,
    Notes:
      "The country code listed is for future use (Vatican is currently using country code '39').",
  },
];
