/**
 * Build-time version stamp generator.
 *
 * Writes a unique version for the current build into two places that must
 * agree per deploy:
 *   1. `src/app/core/version/app-version.ts` — baked into the browser
 *      and server bundles (the "running" version).
 *   2. `public/version.json` — copied to the build output and also served by
 *      the SSR server at `/version.json` (the "deployed" version a client
 *      polls).
 *
 * On a new deploy the value changes, so a client running the previous bundle
 * sees `deployed !== running` and prompts the user to update.
 *
 * Runs automatically before build/start via npm `pre*` hooks (see package.json).
 */
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function shortSha() {
  const envSha =
    process.env.VERCEL_GIT_COMMIT_SHA || process.env.GIT_COMMIT_SHA || process.env.COMMIT_REF;
  if (envSha) return envSha.slice(0, 8);
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return 'local';
  }
}

// Build time makes every deploy unique even if the commit is unchanged
// (e.g. a redeploy), so any new deploy reliably triggers the update prompt.
const version = `${shortSha()}.${Date.now()}`;
const builtAt = new Date().toISOString();

const tsPath = join(root, 'src/app/core/version/app-version.ts');
mkdirSync(dirname(tsPath), { recursive: true });
writeFileSync(
  tsPath,
  `// AUTO-GENERATED by scripts/generate-version.mjs at build time. Do not edit by hand.\n` +
    `export const APP_VERSION = '${version}';\n` +
    `export const APP_BUILT_AT = '${builtAt}';\n`,
);

const jsonPath = join(root, 'public/version.json');
mkdirSync(dirname(jsonPath), { recursive: true });
writeFileSync(jsonPath, `${JSON.stringify({ version, builtAt }, null, 2)}\n`);

console.log(`[generate-version] APP_VERSION=${version}`);
