/**
 * Build-time version stamp generator.
 *
 * Writes build identity into two places that must agree per deploy:
 *   1. `src/app/core/version/app-version.ts` — baked into the browser
 *      and server bundles (the "running" build).
 *   2. `public/version.json` — copied to the build output and also served by
 *      the SSR server at `/version.json` (the "deployed" build a client polls).
 *
 * On a new deploy the id changes, so a client running the previous bundle sees
 * `deployed !== running` and prompts the user to update.
 *
 * Runs automatically before build/start/test/lint via npm `pre*` hooks, and
 * once after install via `prepare` — see package.json. Both outputs are
 * gitignored precisely because they are generated on every one of those paths.
 *
 * See docs/engineering/versioning.md §3.
 */
import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function shortSha() {
  const envSha =
    process.env.VERCEL_GIT_COMMIT_SHA || process.env.GIT_COMMIT_SHA || process.env.COMMIT_REF;
  if (envSha) return envSha.slice(0, 8);
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return 'local';
  }
}

// Read rather than import: `import` of a JSON file would need an import
// attribute, and this value must never reach app code anyway (importing
// package.json into the bundle ships the whole dependency list to the browser).
const { version: semver } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

const sha = shortSha();

// why: the build id is `sha.timestamp`, NOT the bare sha. A redeploy of the same
// commit — a rollback, an env-var change, a retried build — must still trip the
// update prompt, because the running bundle can differ from what is now served.
// A bare sha compares equal across those and the prompt never fires.
const buildId = `${sha}.${Date.now()}`;
const builtAt = new Date().toISOString();

const tsPath = join(root, 'src/app/core/version/app-version.ts');
mkdirSync(dirname(tsPath), { recursive: true });
writeFileSync(
  tsPath,
  `// AUTO-GENERATED by scripts/generate-version.mjs at build time. Do not edit by hand.\n` +
    `// Gitignored: every build, test and lint run regenerates it.\n` +
    // APP_VERSION stays the build id, and stays this name: it is what
    // UpdateChecker compares and what `/version.json` reports as `buildId`.
    `export const APP_VERSION = '${buildId}';\n` +
    `export const APP_SEMVER = '${semver}';\n` +
    `export const APP_SHA = '${sha}';\n` +
    `export const APP_BUILT_AT = '${builtAt}';\n`,
);

const jsonPath = join(root, 'public/version.json');
mkdirSync(dirname(jsonPath), { recursive: true });
writeFileSync(jsonPath, `${JSON.stringify({ version: semver, sha, builtAt, buildId }, null, 2)}\n`);

console.log(`[generate-version] ${semver} ${sha} buildId=${buildId}`);
